//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.27 at 11:37:10 AM GMT-10:00 
//


package org.webcat.eclipse.deveventtracker.sensorbase;

import java.io.Serializable;

public class SensorData
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected long timestamp;
    protected long runtime;
    protected String tool;
    protected String sensorDataType;
    protected String uri;
    private String projectUri;
    protected Properties properties;

	/**
	 * @return the uri
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * @param uri the uri to set
	 */
	public void setUri(String uri) {
		this.uri = uri;
	}

	/**
     * Gets the value of the timestamp property.
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     */
    public void setTimestamp(long value) {
        this.timestamp = value;
    }
    
    /**
     * Gets the value of the runtime property.
     */
    public long getRuntime() {
        return runtime;
    }

    /**
     * Sets the value of the runtime property.
     */
    public void setRuntime(long value) {
        this.runtime = value;
    }


    /**
     * Gets the value of the tool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTool() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTool(String value) {
        this.tool = value;
    }

    public boolean isSetTool() {
        return (this.tool!= null);
    }

    /**
     * Gets the value of the sensorDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorDataType() {
        return sensorDataType;
    }

    /**
     * Sets the value of the sensorDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorDataType(String value) {
        this.sensorDataType = value;
    }

    public boolean isSetSensorDataType() {
        return (this.sensorDataType!= null);
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    public boolean isSetProperties() {
        return (this.properties!= null);
    }


    /**
     * Returns the first Property instance with the specified key, or null if not found.
     * @param key The key for the property of interest. 
     * @return The Property instance for the key, or null if not found. 
     */
    public Property findProperty(String key) {
      for (Property property : this.getProperties().getProperty()) {
        if ((property.getKey() != null) && (property.getKey().equals(key))) {
          return property;
        }
      }
      return null;
    }
    
    /**
     * Adds a new property to this instance with the specified key and value. 
     * @param key The key for the new property.
     * @param value The value for the new property.
     */
    public void addProperty(String key, String value) {
      if (this.getProperties() == null) {
        this.setProperties(new Properties());
      }
      Property property = new Property();
      property.setKey(key);
      property.setValue(value);
      this.getProperties().getProperty().add(property);
    }

	public String getProjectUri() {
		return projectUri;
	}

	public void setProjectUri(String projectUri) {
		this.projectUri = projectUri;
	}

	public String getFileString() {
		String representation = "";
		representation += "<SensorData>" + "\n";
		representation += "<Timestamp>" + "\n";
		representation += timestamp + "\n";
		representation += "</Timestamp>" + "\n";
		representation += "<Runtime>" + "\n";
		representation += runtime + "\n";
		representation += "</Runtime>" + "\n";
		representation += "<Tool>" + "\n";
		representation += tool + "\n";
		representation += "</Tool>" + "\n";
		representation += "<SensorDataType>" + "\n";
		representation += sensorDataType + "\n";
		representation += "</SensorDataType>" + "\n";
		representation += "<URI>" + "\n";
		representation += uri + "\n";
		representation += "</URI>" + "\n";
		representation += "<ProjectURI>" + "\n";
		representation += projectUri + "\n";
		representation += "</ProjectURI>" + "\n";
		if(isSetProperties())
		{
			representation += "<Properties>" + "\n";
			for (Property p : properties.property)
			{
				representation += "<Property>" + "\n";
				representation += "<Name>" + "\n";
				representation += p.key + "\n";
				representation += "</Name>" + "\n";
				representation += "<Value>" + "\n";
				representation += p.value + "\n";
				representation += "</Value>" + "\n";
				representation += "</Property>" + "\n";
			}
			representation += "</Properties>" + "\n";
		}
		representation += "</SensorData>" + "\n";
		return representation;
	}
    
}
